package web;

import dao.SaleDAO;
import domain.Sale;
import io.jooby.Jooby;
import io.jooby.StatusCode;
import io.jooby.annotation.Path;

/**
 *
 * @author Brooklyn
 */
@Path("/api/sales")
public class SaleModule extends Jooby {

    public SaleModule(SaleDAO dao) {

        // create and save sale
        post("/", ctx -> {
            Sale sale = ctx.body().to(Sale.class);
            dao.save(sale);
            //customerId and saleId are generated by database and should be null
            System.out.println("Created sale:" + sale);
            return ctx.send(StatusCode.CREATED);
        });
    }

}
