package web;

import dao.SaleDAO;
import domain.Sale;
import io.jooby.Jooby;
import io.jooby.StatusCode;
import io.jooby.annotation.Path;

/**
 *
 * @author Brooklyn
 */
@Path("/api/sales")
public class SaleModule extends Jooby {

    public SaleModule(SaleDAO dao) {

        // create and save sale
        post("/api/sales/", ctx -> {
            Sale sale = ctx.body().to(Sale.class);
            dao.save(sale);
            //customerId and saleId are generated by database and should be null
//            System.out.println("Created sale: \nSaleID:" + sale.getSaleId()+"\nDate Placed: "+sale.getDate()+"\nCustomer: "+sale.getCustomer().getFirstName()+" "+sale.getCustomer().getSurname()+"\nStatus: "+sale.getStatus()+"\nSale Total:"+sale.getSaleTotal());
            return ctx.send(StatusCode.CREATED);
        });
    }

}
