
CREATE SEQUENCE "PUBLIC"."SEQ_CUSTOMER_ID" START WITH 1 RESTART WITH 33;
CREATE  TABLE "PUBLIC"."CUSTOMER"(

    "CUSTOMERID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000 RESTART WITH 1034) NOT NULL,

    "USERNAME" CHARACTER VARYING(50) NOT NULL,

    "FIRSTNAME" CHARACTER VARYING(20) NOT NULL,

    "SURNAME" CHARACTER VARYING(20) NOT NULL,

    "PASSWORD" CHARACTER VARYING(20) NOT NULL,

    "EMAILADDRESS" CHARACTER VARYING(50) NOT NULL,

    "SHIPPINGADDRESS" CHARACTER VARYING(50) NOT NULL

);
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CUSTOMER_PK" PRIMARY KEY("CUSTOMERID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;
CREATE  TABLE "PUBLIC"."PRODUCT"(

    "PRODUCTID" CHARACTER VARYING(50) NOT NULL,

    "NAME" CHARACTER VARYING(100) NOT NULL,

    "DESCRIPTION" CHARACTER VARYING(255),

    "CATEGORY" CHARACTER VARYING(50) NOT NULL,

    "LISTPRICE" NUMERIC(10, 2) NOT NULL,

    "QUANTITYINSTOCK" NUMERIC(10, 2) NOT NULL

);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."PRODUCT_PK" PRIMARY KEY("PRODUCTID");
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('435', 'Jaw Extender', U&'Is your cats underbit causing too much "tongue issue"?\000aTry this faux jaw extension to put that thing back where it came from!', 'Medical', 78.99, 32.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('756', 'A4 Boris Print', U&'Get a personalised Boris Photo to display in your home!\000aComes with a personal message and signed paw print', 'Pictures', 19.99, 100.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('875', 'Leg ReBoner', U&'Has rickets got your Boris down?\000aOur special leg reboner manages to straighten\000aand rebone his rickety wrecked legs back to new', 'Medical', 12.49, 20.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('1023', 'Boris Translator', U&'Tired of incomprehensible "brrt"s and "mrrrow"s?\000a\000aOur special translator gadget manages to convert those \000acat noises into human speech!\000a\000aNote we are not responsible for the amount of profanity \000ayou will hear from your Boris', 'Gadget', 849.99, 12.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('7684', 'Boris', U&'The mad legend himself, now for consumer purchase!\000a\000aNow you can own your very own Boris to take home and \000aadmire the constant noises and tongue sticking out!', 'Animals', 199.99, 1.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('736', '4x6 Boris Prints', 'Tiny Boris pictures perfect for take home gifts!', 'Pictures', 5.99, 149.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('9678', 'Boris Bands', U&'Tired of staring endlessly into those enormous black pools?\000a\000aWith the Boris Bands, and patent pending strap, you can hide \000afrom his endless gaze', 'Clothing', 32.49, 43.00);
-- INSERT INTO "PUBLIC"."PRODUCT"("PRODUCTID", "NAME", "DESCRIPTION", "CATEGORY", "LISTPRICE", "QUANTITYINSTOCK") VALUES('924', 'Boris Cozy''s', U&'Being a small cat, your Boris is prone to the cold.\000aSnug him up with our patent pending Chinese newspaper\000astuffed winter jacket for those lonely nights.', 'Clothing', 7.99, 85.00);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" CHECK("QUANTITYINSTOCK" >= CAST(0 AS NUMERIC(1))) NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" CHECK("LISTPRICE" >= CAST(0 AS NUMERIC(1))) NOCHECK;
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" UNIQUE("USERNAME");